### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by vekrasikov** [TyumenBonaventura/Mr.ProPr#1]
Какая-то ахинея с апи. Самое первое, что бросается в глаза, очень странный расчёт числа Фибоначчи

**Comment by TyumenBonaventura** [comment]
Формулу для Фибоначчи я нашёл [здесь](https://stackoverflow.com/questions/15600041/php-fibonacci-sequence), в комментарии к ответу, отмеченным галочкой.

В файле .htaccess я настроил вид запросов под каждую функцию. На моем компьютере они выглядят так:

http://localhost/ProPr/lab1/path/parameter/8 - возврат параметра 8,
http://localhost/ProPr/lab1/fibonacci/3 - вычисление числа Фибоначчи для 3,
http://localhost/ProPr/lab1/quadratic/url?a=1&b=4&c=2 - решение квадратного уравнения для a=1, b=4, c=2,
http://localhost/ProPr/lab1/region/01 - вернёт регион с кодом 01 (республика Бурятия),
http://localhost/ProPr/lab1/weekday/url?date=18.04.2019 - вернёт день недели для сегодняшней даты.

**Comment by TyumenBonaventura** [comment]
Только сейчас заметил, что .htaccess не был загружен сразу. Загрузил, теперь должно работать.
